FROM containerbase/buildpack@sha256:ae411ab0b74176c3db1d9213cd5d40e57b03b77d56375702ee05379a437ac742

# renovate: datasource=docker versioning=docker
RUN install-tool node 14.16.1 \
# renovate: datasource=npm
  && install-tool yarn 1.22.10